### ISSUE TITLE
How do I generate the correct type of diff file?

### ISSUE THREAD

**Issue by jononomo** [juliancwirko/meteor-pretty-diff-app#1]
I create a fill called `changes.diff` by running `git diff some_file > changes.diff` at the command line.  Then I upload this file to the demo app.  I then get an error message saying: "Unsupported media type. Supported file types are: text/plain, text/x-diff, text/x-patch"

What did I do wrong?

**Comment by juliancwirko** [comment]
Hm, hard to say. It works for me. It must have wrong format somehow. 
Maybe try with `.txt` extension.
